app:
  port:
    8000
  graceful_timeout:
    30
  system_server_port:
    8001
  api_secret_key:
    your_api_secret_key
  auth_base_url:
    your_auth_base_url
mongo:
  url: mongodb://root:secret@app_mongo:27017
  db_name: boilerplate
  time_out: 30
collection:
  brand: brands
  user: users