version: '3.3'

services:
  mongo:
    image: mongo:3.6
    container_name: app_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./storage/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  app:
    build: .
    image: go-rest-api:latest
    container_name: app_server
    volumes:
       - ./config.yaml:/etc/go-rest-api/app.config.yaml
    ports:
       - "8080:8080"
       - "3550:3550"
    command: 'serve-rest --config /etc/go-rest-api/app.config.yaml'
