version: '3.3'

services:
  mongo:
    image: mongo:3.6
    restart: always
    expose:
      - "27017"
    volumes:
      - ./storage/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD

  redis:
    image: redis:7.0.11
    restart: always
    expose:
      - "6379"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  backend:
    build: .
    image: anr35/go-rest-api:latest
    depends_on:
      - mongo
      - redis
    volumes:
       - ./config.yml:/etc/go-rest-api/config.yml
    ports:
       - "8000:8000"
    command: 'serve-rest --config /etc/go-rest-api/config.yml'
