app:
  port:
    8000
  graceful_timeout:
    30
  system_server_port:
    8001
  api_secret_key:
    your_api_secret_key
  auth_base_url:
    your_auth_base_url
  access_token_expires_in:
    300
mongo:
  db_name: boilerplate_test
  time_out: 30
  env:
    host: MONGODB_HOST
    port: MONGODB_PORT
    user_name: MONGODB_USERNAME
    password: MONGODB_PASSWORD
redis:
  db_id: 0
  time_out: 30
  env:
    host: REDIS_HOST
    port: REDIS_PORT
collection:
  brand: brands
  user: users