app:
  port:
    8000
  graceful_timeout:
    30
  system_server_port:
    8001
  api_secret_key:
    your_api_secret_key
  auth_base_url:
    your_auth_base_url
  access_token_expires_in:
    300
mongo:
  url: mongodb://root:secret@localhost:27017
  db_name: boilerplate
  time_out: 30
redis:
  url: localhost:6379
  db_id: 0
  time_out: 30
collection:
  brand: brands
  user: users