name: Go-rest-api CI

on:
  push:
    branches:
      - "e2e_test"
env:
  GITHUB_WORKSPACE: /home/runner/work/go-rest-api/go-rest-api

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: run containers
        run: |
          docker-compose -f "docker-compose-dev.yml" up -d --build

      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.1'

      - name: install dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: run tests
        run: |
          cd e2e_test
          go test --config=../test.config.yml -ginkgo.v

      - name: stop containers
        run: |
          docker-compose -f "docker-compose-dev.yml" down