name: Github CI

on:
  push:
    branches:
      - "PER-2-workflow-test"
env:
  GITHUB_WORKSPACE: /home/runner/work/go-rest-api/go-rest-api
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: run containers
        run: |
          docker-compose -f "docker-compose-dev.yml" up -d --build
      - name: run tests
        run: |
          cd e2e_test
          go test --config=../test.config.yaml -ginkgo.v
      - name: stop containers
        run: |
          docker-compose -f "docker-compose-dev.yml" down