name: Github CI

on:
  push:
    branches:
      - "PER-2"
jobs:
  build_and_upload_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build -t anr35/go-rest-api -f Dockerfile.dev .
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
      - name: push to docker hub
        run: |
          docker push anr35/go-rest-api

