name: Github CI

on:
  push:
    branches:
      - "PER-2-workflow-test"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build -t anr35/go-rest-api -f Dockerfile.dev .
      - name: run backend server
        run: |
          docker run -e CI=true anr35/go-rest-api
      - name: run tests
        run: |
          cd e2e_test
          go test --config=../test.config.yaml -ginkgo.v
      - name: stop server
        run: |
          docker stop anr35/go-rest-api