name: Go-rest-api CI

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "master"
      - "develop"

env:
  GITHUB_WORKSPACE: /home/runner/work/go-rest-api/go-rest-api

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.1'

      - name: run tests
        run: |
          go test $(go list ./... | grep -v go-rest-api/e2e_test) -v

  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: run containers
        run: |
          docker-compose -f "docker-compose-dev.yml" up -d --build

      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.1'

      - name: install dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: run tests
        run: |
          cd e2e_test
          go test --config=../test.config.yml -ginkgo.v --env=test

      - name: stop containers
        run: |
          docker-compose -f "docker-compose-dev.yml" down

  build_and_upload_image:
    if: ${{ (github.event.pull_request.merged == true) && ((github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/develop')) }}
    runs-on: ubuntu-latest
    needs:
      - unit_test
      - integration_test

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: build docker image
        run: |
          docker build -t anr35/go-rest-api -f Dockerfile .

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin

      - name: push to docker hub
        run: |
          docker push anr35/go-rest-api

